/** Single source of truth for approved rebates awaiting an E-Moto Possession Statement.
 * Used by both the AF's PossessionConfirmationView and the Analyst/QA PossessionAnalysisView,
 * so a ticket submitted on one side is always the same ticket reviewable on the other. */

export interface ApprovedPossessionCase {
  ticketNumber: string;
  assetFinancier: string;
  submittedBy: string;
  firstName: string;
  lastName: string;
  nationalId: string;
  motoLicense: string;
  isWoman: boolean;
  isRetrofit: boolean;
  supplier: string;
  model: string;
  retrofitAssembler: string;
  retailCost: number;
  rebateAmount: number;
  supportingDocuments: string[];
  affidavitUploaded: boolean;
  iceAgreementUploaded: boolean | null; // null = N/A for new e-moto
  phone?: string;
  email?: string;
  qaApprovedAt: string;
}

export const APPROVED_POSSESSION_CASES: ApprovedPossessionCase[] = [
  {
    ticketNumber: 'REB-001',
    assetFinancier: 'Bank of Kigali',
    submittedBy: 'Pamela Mugabe',
    firstName: 'Jean Claude',
    lastName: 'Ndayisaba',
    nationalId: '1198780012345678',
    motoLicense: 'DL-2024-1022',
    isWoman: false,
    isRetrofit: false,
    retailCost: 830000,
    rebateAmount: 150000,
    supplier: 'Ampersand',
    model: 'AMP-E2',
    retrofitAssembler: 'N/A',
    supportingDocuments: ['Signed financing contract', 'National ID'],
    affidavitUploaded: true,
    iceAgreementUploaded: null,
    phone: '+250-788-1001',
    email: 'j.ndayisaba@example.rw',
    qaApprovedAt: '2026-06-01',
  },
  {
    ticketNumber: 'REB-002',
    assetFinancier: 'Bank of Kigali',
    submittedBy: 'Grace Mukandori',
    firstName: 'Grace',
    lastName: 'Uwase',
    nationalId: '1198780098765432',
    motoLicense: 'DL-2023-8831',
    isWoman: true,
    isRetrofit: true,
    retailCost: 800000,
    rebateAmount: 200000,
    supplier: 'Spiro',
    model: 'SP-Retrofit',
    retrofitAssembler: 'REM',
    supportingDocuments: ['Retrofit suitability statement'],
    affidavitUploaded: true,
    iceAgreementUploaded: true,
    phone: '+250-788-1002',
    email: 'g.uwase@example.rw',
    qaApprovedAt: '2026-06-02',
  },
  {
    ticketNumber: 'REB-003',
    assetFinancier: 'Bank of Kigali',
    submittedBy: 'Grace Mukandori',
    firstName: 'Alice',
    lastName: 'Mutoni',
    nationalId: '1198780055500000',
    motoLicense: 'DL-2024-2200',
    isWoman: true,
    isRetrofit: false,
    retailCost: 700000,
    rebateAmount: 175000,
    supplier: 'Spiro',
    model: 'Commuter',
    retrofitAssembler: 'N/A',
    supportingDocuments: ['Signed financing contract'],
    affidavitUploaded: true,
    iceAgreementUploaded: null,
    phone: '+250-788-1007',
    email: 'a.mutoni@example.rw',
    qaApprovedAt: '2026-03-20',
  },
  {
    ticketNumber: 'REB-004',
    assetFinancier: 'Bank of Kigali',
    submittedBy: 'Kevin Agent',
    firstName: 'Jean',
    lastName: 'Habimana',
    nationalId: '1198780066600000',
    motoLicense: 'DL-2024-3300',
    isWoman: false,
    isRetrofit: false,
    retailCost: 600000,
    rebateAmount: 150000,
    supplier: 'Ampersand',
    model: 'AMP-E2',
    retrofitAssembler: 'N/A',
    supportingDocuments: ['Signed financing contract'],
    affidavitUploaded: true,
    iceAgreementUploaded: null,
    phone: '+250-788-1008',
    email: 'j.habimana@example.rw',
    qaApprovedAt: '2026-05-01',
  },
  {
    ticketNumber: 'REB-005',
    assetFinancier: 'Equity Bank',
    submittedBy: 'James Uwizeye',
    firstName: 'Marie Claire',
    lastName: 'Uwimana',
    nationalId: '1198780033333333',
    motoLicense: 'DL-2025-4201',
    isWoman: true,
    isRetrofit: false,
    retailCost: 750000,
    rebateAmount: 187500,
    supplier: 'Safi',
    model: 'City',
    retrofitAssembler: 'N/A',
    supportingDocuments: ['AF confirmation of financial need'],
    affidavitUploaded: true,
    iceAgreementUploaded: null,
    phone: '+250-788-1003',
    email: 'm.uwimana@example.rw',
    qaApprovedAt: '2026-06-03',
  },
  {
    ticketNumber: 'AF-BOK-1',
    assetFinancier: 'Bank of Kigali',
    submittedBy: 'Pamela Mugabe',
    firstName: 'Patrick',
    lastName: 'N',
    nationalId: '1198780070707070',
    motoLicense: 'DL-2024-5500',
    isWoman: false,
    isRetrofit: false,
    retailCost: 3500000,
    rebateAmount: 630000,
    supplier: 'Ampersand',
    model: 'Pro',
    retrofitAssembler: 'N/A',
    supportingDocuments: ['Signed financing contract', 'Mobile money statement'],
    affidavitUploaded: true,
    iceAgreementUploaded: null,
    phone: '+250-788-1004',
    email: 'patrick.n@example.rw',
    qaApprovedAt: '2026-06-14',
  },
  {
    ticketNumber: 'AF-EQB-12',
    assetFinancier: 'Equity Bank',
    submittedBy: 'Divine Agent',
    firstName: 'Divine',
    lastName: 'Mukamana',
    nationalId: '1198780099999999',
    motoLicense: 'DL-2024-6600',
    isWoman: true,
    isRetrofit: true,
    retailCost: 2900000,
    rebateAmount: 725000,
    supplier: 'Rem',
    model: 'Retrofit Kit',
    retrofitAssembler: 'Safi',
    supportingDocuments: ['ICE disposal agreement'],
    affidavitUploaded: true,
    iceAgreementUploaded: true,
    phone: '+250-788-1005',
    email: 'd.mukamana@example.rw',
    qaApprovedAt: '2026-06-05',
  },
  {
    ticketNumber: 'AF-REM-8',
    assetFinancier: 'REM',
    submittedBy: 'Claire Mukamana',
    firstName: 'Eric',
    lastName: 'Habimana',
    nationalId: '1198780044444444',
    motoLicense: 'DL-2023-7700',
    isWoman: false,
    isRetrofit: true,
    retailCost: 2800000,
    rebateAmount: 560000,
    supplier: 'Rem',
    model: 'Retrofit Kit',
    retrofitAssembler: 'Rem',
    supportingDocuments: ['Retrofit suitability statement'],
    affidavitUploaded: true,
    iceAgreementUploaded: true,
    phone: '+250-788-1006',
    email: 'e.habimana@example.rw',
    qaApprovedAt: '2026-06-01',
  },
];
